### ISSUE TITLE
第一!

### ISSUE THREAD

**Issue by shaokeyibb** [kasuganosoras/SakuraFrp-BBS#2]
| SakuraFrp搬迁论坛到github祝贺 | 
| 闲聊 |
| 原创? |
第一贴。。。话说近期把论坛设到github好潮流的说
不管怎么说SakuraFrp是真的给力

**Comment by chisaato** [comment]
需要搞个大新闻.

**Comment by kasuganosoras** [comment]
请勿水贴 /手动滑稽
