### ISSUE TITLE
GitHub搭论坛,讲究xd

### ISSUE THREAD

**Issue by Hallon233** [kasuganosoras/SakuraFrp-BBS#4]
| 帖子主题 | 水一贴 |
| --- | --- |
| 主题分类 | 闲聊 |
| 内容类型 | 原创 |
| 原贴地址 | www.github.com |

我本来还以为是github.io,没想到直接用issue
![tim 20181014224545](https://user-images.githubusercontent.com/28214389/46918281-eed13480-d002-11e8-8dc0-02e3308f463d.jpg)

**Comment by kasuganosoras** [comment]
毕竟Issues方便，而且也具有论坛差不多的功能

**Comment by FunCraft001** [comment]
出现了讲究怪

**Comment by NicholasLD** [comment]
![k0v_ p8 p 5l x k 1e a](https://user-images.githubusercontent.com/36059320/46918349-e0cfe380-d003-11e8-820f-f6bf5ec3f50e.jpg)
